#
# Copyright (c) 2022 Achim Kraus CloudCoap.net
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: eclipse
      url-base: https://github.com/boaks
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v2.9.0
      import:
        name-blocklist:
          - matter
          - nrf-802154
          - openthread
          - cmock
          - unity
          - cddl-gen
          - homekit
          - loramac-node
          - lz4
          - lvgl
          - mipi-sys-t
    - name: tinydtls
      submodules: true
      repo-path: tinydtls
      remote: eclipse
      revision: zephyr_cid_develop
      path: modules/lib/tinydtls
  self:
    path: coaps-client
